### ISSUE TITLE
is there a way to use `input_options`?

### ISSUE THREAD

**Issue by l0c0luke** [daichirata/paperclip-streamio-ffmpeg#1]
i would like to use `-stream_loop 3` but it needs to be used as an input option according to the streamio-ffmpeg library... is there a way to do that with this library?

**Comment by daichirata** [comment]
Sorry for the late reply. options to streamio-ffmpeg can be specified in `convert_options`.

```ruby
styles: {
  thumb: {
    format: :jpeg,
    convert_options: {
      resolution: "150x150",
      screenshot: true,
      seek_time: 3,
    }
    transcoder_options: {
      preserve_aspect_ratio: :width
    }
  },
```

Please let me know if there is any problem.
